### ISSUE TITLE
API for get a list of products from specific vendor

### ISSUE THREAD

**Issue by xu4wang** [spree/spree_multi_vendor#103]
Dear All,

Is there an API to get a list of products from one specific vendor?
In the storefront API, there is one 
http://localhost:3000/api/v2/storefront/products

However, it returns all the products, is there a similar API for multi-vendor extension? or should we make another extension for this?

BR,Austin

**Comment by damianlegawiec** [comment]
Hey @xu4wang 

To accomplish this we would need to add a vendor filter to the [Product Finder class](https://github.com/spree/spree/blob/master/core/app/finders/spree/products/find.rb) similarly as it's done for Taxon(s):

https://github.com/spree/spree/blob/416e555ab197d334e7e1c1d8e803b3472f8b9a68/core/app/finders/spree/products/find.rb#L11

**Comment by xu4wang** [comment]
OK. thanks for the information. I will try to implement this.

**Comment by SwissMich10** [comment]
Hi @xu4wang! Were you able to implement this? If so, how?

**Comment by xu4wang** [comment]
Yes. I followed the instruction from @damianlegawiec and made it.

I need some time to find the implementation.. didn't use spree for a while.

**Comment by poudelprakash** [comment]
@xu4wang I have submitted a PR to fetch vendor details via v2 api: https://github.com/spree-contrib/spree_multi_vendor/pull/156/files
This api also responds with products of vendor
sample url:
```
http://localhost:3000/api/v2/storefront/vendors/:slug?include=products
```

**Comment by coolprobn** [comment]
Hey @damianlegawiec @xu4wang I have submitted a pull request for this here: https://github.com/spree-contrib/spree_multi_vendor/pull/157
