### ISSUE TITLE
error creating vendor when globalize is installed

### ISSUE THREAD

**Issue by xu4wang** [spree/spree_multi_vendor#104]
My multi vendor installation was working well until today I installed 
https://github.com/spree-contrib/spree_globalize

When creating a new vendor, it complains that:

```
NameError in Spree::Admin::VendorsController#create
undefined local variable or method `translation_class' for #<ActiveRecord::Relation []>
```

The created vendors are still working well, but cannot create new vendor.

**Comment by drkpkg** [comment]
Yeah, I figure it out days ago. Is problem from globalize gem from spree.
Create a migration file and add:
```
class AddTranslationToVendor < ActiveRecord::Migration[6.0]
  def up
    unless table_exists?(:spree_vendor_translations)
      params = { name: :string, about_us: :text, contact_us: :text, slug: :string }
      Spree::Vendor.create_translation_table!(params, { migrate_data: true })
    end
  end

  def down
    Spree::Vendor.drop_translation_table! migrate_data: true
  end
end
```
And then in models/spree add a decorator called vendor_decorator.rb:
```
module Spree::VendorDecorator
  def self.prepended(base)
    base.translates :name, :about_us, :contact_us, :slug, fallbacks_for_empty_translations: true
  end

  Spree::Vendor.include SpreeGlobalize::Translatable
end

::Spree::Vendor.prepend(Spree::VendorDecorator)
```

This is the patch solution, maybe later If I have time this will be an PR for globalize gem.

**Comment by xu4wang** [comment]
thanks @drkpkg for the quick patch. I will try it later.

I think this issue should be handled inside spree_multi_vendor extension instead of globalize extension. 
The reason is globalize extension may not have knowledge of the extensions installed.  but spree_multi_vendor need to be globalize friendly.

Is there a general requirement for any extension to be globalize extension friendly? 

As an example, I found in https://github.com/spree-contrib/spree_static_content , the migration generated is with 

> if defined?(SpreeGlobalize)

**Comment by drkpkg** [comment]
Thanks for the answer @xu4wang, spree_multi_vendor doesn't need the globalize gem dependency, so if the gem add it as default maybe will break some deployed systems in my perspective. I'm thinking in a new gem as patch that can be work with spree_multi_vendor without break the migrations in case globalize will not be in the dependencies. Gonna try something tomorrow and will post the results here :)

**Comment by drkpkg** [comment]
Well, I make the PR into master, I hope this will works well and don't break another implementations with spree multi vendor :)

Feel free to suggest!

**Comment by xu4wang** [comment]
> Yeah, I figure it out days ago. Is problem from globalize gem from spree.
> Create a migration file and add:
> 
> ```
> class AddTranslationToVendor < ActiveRecord::Migration[6.0]
>   def up
>     unless table_exists?(:spree_vendor_translations)
>       params = { name: :string, about_us: :text, contact_us: :text, slug: :string }
>       Spree::Vendor.create_translation_table!(params, { migrate_data: true })
>     end
>   end
> 
>   def down
>     Spree::Vendor.drop_translation_table! migrate_data: true
>   end
> end
> ```
> 
> And then in models/spree add a decorator called vendor_decorator.rb:
> 
> ```
> module Spree::VendorDecorator
>   def self.prepended(base)
>     base.translates :name, :about_us, :contact_us, :slug, fallbacks_for_empty_translations: true
>   end
> 
>   Spree::Vendor.include SpreeGlobalize::Translatable
> end
> 
> ::Spree::Vendor.prepend(Spree::VendorDecorator)
> ```
> 
> This is the patch solution, maybe later If I have time this will be an PR for globalize gem.

I verified the patch solution with current release of Spree, globalize,multi-vendor gem. So far so good.  Thanks @drkpkg !

**Comment by drkpkg** [comment]
The Pull request was approved, now we have support for spree globalize :)

**Comment by thomaseude** [comment]
Hello, I'm facing an issue relating to this ticket (I think)

I'm getting an error when I want to access Vendor in the admin panel 
![image](https://user-images.githubusercontent.com/54139531/81485938-820b3400-9251-11ea-8045-90535122354a.png)

This is the error:
![image](https://user-images.githubusercontent.com/54139531/81485954-ac5cf180-9251-11ea-966f-aa68c2b8da94.png)

Normally my gem is up to date! My migration look like that
```
class AddTranslationsToVendor < ActiveRecord::Migration[4.2]
  def up
    params = { name: :string, about_us: :text, contact_us: :text, slug: :string }
    if defined?(SpreeGlobalize)
      Spree::Vendor.create_translation_table!(params, { migrate_data: true })
    end
  end
end
```
Compare to your code above, I don't know if the difference has an impact ? 
1/ 
```
unless table_exists?(:spree_vendor_translations)

end
```
2/ The name of the migration has no "s" for translate in your code above but has one in migration of your PR
![image](https://user-images.githubusercontent.com/54139531/81485870-001b0b00-9251-11ea-8082-20f71dc711db.png)

Any tips ? 
Thanks for letting me know 🍻

**Comment by drkpkg** [comment]
If you follow the proccess of install will be ok. I try in a clean installation and I can't reproduce the error.

If you have the patch code I write before delete it and use the clean install of the gem.

```bash
bundle exec rails g spree_multi_vendor:install
```

**Comment by thomaseude** [comment]
I have still some troubles with translating, but at least it resolve this problem

Thanks a lot for your help :)

**Comment by thomaseude** [comment]
Does it work for you when you want to update a vendor ? (Name, Slug, State, ..) 

With the current code, if I want to update a vendor, this is the error
![image](https://user-images.githubusercontent.com/54139531/81850954-02cf7600-9559-11ea-8e81-c59dabd55d82.png)

To resolve the problem, I just remove this line and all look to work fine
![image](https://user-images.githubusercontent.com/54139531/81851033-22ff3500-9559-11ea-8ce8-240e925bb38d.png)

What about you ?
