### ISSUE TITLE
Cannot checkout a product if the product belongs to a vendor.

### ISSUE THREAD

**Issue by drkpkg** [spree/spree_multi_vendor#108]
I try the store flow and the product cannot pass the delivery into the checkout cart flow.

Steps:
- Create a product and made it visible into the store with stock, assign it to a vendor
- Go to the store and select the product to checkout
- Proceed the checkout and is there when it fails.

I configure the zones and the stock locations, payment methods and delivery options are ok with products that doesn't have a vendor assigned.

I tested again, it's the vendor location itself. If I create the product without vendor and later assign a vendor, add stock in the new location it will works, but it never takes the product stock from the vendor stock location, it takes from the default stock location.

Video about the issue:
https://drive.google.com/file/d/1G4d1vRygTB4ffd0PgcDz1e1YRrryhXa6/view?usp=sharing

**Comment by kudapara** [comment]
Do you mind sharing how you fixed the issue?
