### ISSUE TITLE
Error when click on Properties menu as a vendor (when i have installed multivendor extension)

### ISSUE THREAD

**Issue by avadhesh82** [spree/spree_multi_vendor#111]
Error when click on Properties menu as a vendor (when i have installed multivendor extension)
![properties-error](https://user-images.githubusercontent.com/20087909/80701444-0694de80-8afd-11ea-926f-2ba9e2723ba3.png)

**Comment by avadhesh82** [comment]
you can follow this link for adding this code this location and better way you can copy  full code of admin folder  after that  product/_index.erb page has replaced given this link
https://github.com/spree-contrib/spree_multi_vendor/edit/master/app/views/spree/admin/products/index.html.erb

**Comment by Tashows** [comment]
I had the same error, copied this view and it worked. Still not sure what caused it. Here is the view link:
https://github.com/spree-contrib/spree_multi_vendor/blob/master/app/views/spree/admin/properties/index.html.erb

Also adding the error message in text so other can find this more easily in the future: ActionView::SyntaxErrorInTemplate in Spree::Admin::PropertiesController#index

**Comment by damianlegawiec** [comment]
fixed in 2.0
