### ISSUE TITLE
I want crud operation for vendor. 

### ISSUE THREAD

**Issue by niteshthakare** [spree/spree_multi_vendor#114]
I didn't see Vendor module in spree. I want perform crud operation for vendor module. Please help out if i am doing wrong. 

![Screenshot from 2020-05-16 18-26-18](https://user-images.githubusercontent.com/25428200/82120329-d27b1800-97a2-11ea-802b-7d41ebf3a6c9.png)
![Screenshot from 2020-05-16 18-26-13](https://user-images.githubusercontent.com/25428200/82120333-d4dd7200-97a2-11ea-8daa-db60cda7b7ec.png)

**Comment by mwlalata** [comment]
have you figured this out? Im also looking for the vendor functionality as stated in their docs:

![image](https://user-images.githubusercontent.com/18679035/83354631-8af0b080-a38c-11ea-9043-7fcb35c2c776.png)
