### ISSUE TITLE
All Option Types that are the same shows up on Product Index page 

### ISSUE THREAD

**Issue by SwissMich10** [spree/spree_multi_vendor#134]
If two vendors sell the same kind of product with the same option types, both have to make separate option types for the same kind of options, eg sizes, yet both option types show up on the product index page. For example, Vendor A sells red shirts and Vendor B sells blue shirts. Both carry s, m, & lg sizes, which means both have to create separate Option Types. Vendor A created his option type named Size, presentation name Size, & the sizes are sm, med, & lg. Vendor B created his option type, but can't use the name Size, so he has to use Sizes. However, the presentation name is Size & he carries the same sizes. When you look on the product index page, both option types are there, with the same name and size options. Is there a way the super admin can make the option types and all vendors have access to that, instead of them making the same kind of option types that will show up repeatedly on the product index page?
![Screen Shot 2020-09-25 at 7 43 48 PM](https://user-images.githubusercontent.com/71193664/94299384-e2ccac00-ff67-11ea-846c-ccb3b20c7612.png)

**Comment by damianlegawiec** [comment]
fixed in 2.0
