### ISSUE TITLE
undefined method vendor_path for product

### ISSUE THREAD

**Issue by MateoLa** [spree/spree_multi_vendor#145]
You add the add_vendor_info_to_products_show.rb override but there is no routes to vendor in config/routes.rb

May be you could add to your config/routes.rb: 
    Spree::Core::Engine.add_routes do
       resources :vendors, only: :show
    end

..and would be right adding a controller and the view for the show action.

**Comment by githubble01** [comment]
Possibly encountered the same issue from a different angle #153.

**Comment by damianlegawiec** [comment]
Fixed, please update the gem
