### ISSUE TITLE
undefined method `vendor_path'

### ISSUE THREAD

**Issue by githubble01** [spree/spree_multi_vendor#153]
Hi!

I just bumped into this error after having cranked up a fresh spree store locally. Possibly related to #145. 

### How to reproduce

1. Set up spree store with sample data according to the getting [started guide](https://guides.spreecommerce.org/developer/tutorials/getting_started_tutorial.html). 
2. Set up multi-vendor extension according to the [installation instructions](https://github.com/spree-contrib/spree_multi_vendor#installation), creating a test vendor.
3. Assigned the sample product a-line-suede-skirt to the test vendor.
4. Clicked on the product a-line-suede-skirt in the store front.

### Result

<img width="1217" alt="Screenshot 2020-12-02 at 08 22 57" src="https://user-images.githubusercontent.com/1576706/100841977-68913a00-3478-11eb-96b9-27847cbe54d0.png">

### Gemfile

```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'


gem 'spree', '~> 4.1'
gem 'spree_auth_devise', '~> 4.2'
gem 'spree_gateway', '~> 3.9'

gem 'spree_i18n', github: 'spree-contrib/spree_i18n'
gem 'spree_multi_vendor', github: 'spree-contrib/spree_multi_vendor'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3', '>= 6.0.3.4'
# Use sqlite3 as the database for Active Record
gem 'sqlite3', '~> 1.4'
# Use Puma as the app server
gem 'puma', '~> 4.1'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 4.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]


```

**Comment by sseerrggii** [comment]
Same problem here

**Comment by NaofalMufid** [comment]
i have same problem, try add this routes.rb
  Spree::Core::Engine.add_routes do
    resources :vendors, only: :show
  end
 same issue on [145](https://github.com/spree-contrib/spree_multi_vendor/issues/145)

**Comment by Tashows** [comment]
Yes adding the route solves it but how is this in the codebase if it just crashes? There is also no Spree::VendorsController defined. I don't mind creating my own, I just think it is odd, that there are overrides and views that are made to work with code that is actually missing.

**Comment by damianlegawiec** [comment]
Fixed, please run `bundle update spree_multi_vendor`
