### ISSUE TITLE
 missing keyword: :current_currency in -> ArgumentError in module ProductsFinderDecorator

### ISSUE THREAD

**Issue by old-software-engineer** [spree/spree_multi_vendor#195]
missing keyword: :current_currency in this method ->ArgumentError in module ProductsFinderDecorator

When i implement the spree_multi_vendor gem then on product show page there will be throw error -> missing keyword: :current_currency

**Comment by damianlegawiec** [comment]
this is fixed in the main branch, we need to release it on rubygems

**Comment by w3villa-harshita** [comment]
@damianlegawiec, is it possible to use the main branch directly till release is done?

**Comment by myousry22** [comment]
@damianlegawiec @sharmaparas4444 
<img width="1127" alt="Screen Shot 2021-09-18 at 2 04 36 AM" src="https://user-images.githubusercontent.com/26511051/133864877-701bd7d4-8c67-489d-9f49-b586d89bd997.png">

i have the same issue

**Comment by jakub-polak** [comment]
@damianlegawiec hi! When could we expect a bug fix to be released?

**Comment by djdarkbeat** [comment]
@jakub-polak You can add `Spree::Config.currency` as the argument being sent by `currency:`. We did this initially, in our local gem in `~/.rbenv/..etc` to fix the problem. I was going to fork `v2.2.0` and issue a PR with this change but ultimately we changed our Gemfile

from

```ruby
gem "spree_multi_vendor"
``` 

to 

```ruby
gem "spree_multi_vendor", github: "spree-contrib/spree_multi_vendor", branch: "main"
``` 

And this solved the issue. We had recently updated to Spree 4.3 and got out gem pinned back on `v2.2.0` as that's the last release and was from May.

**Comment by damianlegawiec** [comment]
Hi @sharmaparas4444 @MuhammedYousryKamel  @jakub-polak @djdarkbeat 

`v2.3.0` with Spree 4.3 fixes was pushed to RubyGems

```
bundle update spree_multi_vendor
```

should resolve this issue
