### ISSUE TITLE
undefined method `vendor' when creating a new vendor

### ISSUE THREAD

**Issue by TeamW3villa** [spree/spree_multi_vendor#196]
Getting NoMethodError `(undefined method vendor' for nil:NilClass)`: when creating a new vendor while few days back same code was working Pointing error to `module SpreeMultiVendor::Spree::VariantDecorator` at line 10

**Comment by German8cock** [comment]
Excited

**Comment by 6645594094** [comment]
Pelayodurana@gmail.com
