### ISSUE TITLE
NameError (uninitialized constant Spree::BaseMailer)  occurs when referencing `Spree::VendorMailer`

### ISSUE THREAD

**Issue by hoshinotsuyoshi** [spree/spree_multi_vendor#208]
NameError: uninitialized constant Spree::BaseMailer

## Context

1.  Open `rails c` 
2. Type `Spree::VendorMailer` and press return key.

## Expected Behavior

no error

## Actual Behavior

`NameError: uninitialized constant Spree::BaseMailer` 

### Possible Fix way 1.

before:

```
gem 'spree_multi_vendor'
```

↓

after:

```
gem 'spree_multi_vendor', require: ['spree_emails', 'spree_multi_vendor']
```

### Possible Fix way 2.

before:

```
gem 'spree_multi_vendor'
```

↓

after:

```
gem 'spree_emails'
gem 'spree_multi_vendor'
```

### Possible Fix way 3.

I'll send PR!

## Steps to Reproduce

See above `Context` 

## Your Environment

* Version used: spree 4.3.0, spree_multi_vendor 2.3.0

ruby: 3.0.3
rails: 6.1.4.4

**Comment by damianlegawiec** [comment]
We should include `spree_emails` as a dependency of this gem

**Comment by hoshinotsuyoshi** [comment]
Yes, I make a patch now

**Comment by hoshinotsuyoshi** [comment]
I sent a small PR https://github.com/spree-contrib/spree_multi_vendor/pull/209  

@damianlegawiec  thanks!
