### ISSUE TITLE
uninitialized constant Spree::Api::V1::BaseController (NameError)

### ISSUE THREAD

**Issue by nmella** [spree/spree_multi_vendor#223]
```
ruby '3.2.0'
gem 'rails', '~> 7'
gem 'spree', '~> 4.6'
gem 'spree_backend', '~> 4.6'
gem 'spree_frontend'
gem 'spree_multi_vendor', :github => 'spree-contrib/spree_multi_vendor', :branch => 'main'
```

After executing:

```
bundle exec rails g spree_multi_vendor:install
```

Returned:

```ruby
/bundle/ruby/3.2.0/bundler/gems/spree_multi_vendor-2a2dc0854589/app/controllers/spree/api/v1/vendors_controller.rb:4:in `<module:V1>': uninitialized constant Spree::Api::V1::BaseController (NameError)

      class VendorsController < Spree::Api::V1::BaseController
                                              ^^^^^^^^^^^^^^^^
Did you mean?  Spree::CmsPagesController
	from /bundle/ruby/3.2.0/bundler/gems/spree_multi_vendor-2a2dc0854589/app/controllers/spree/api/v1/vendors_controller.rb:3:in `<module:Api>'
	from /bundle/ruby/3.2.0/bundler/gems/spree_multi_vendor-2a2dc0854589/app/controllers/spree/api/v1/vendors_controller.rb:2:in `<module:Spree>'
	from /bundle/ruby/3.2.0/bundler/gems/spree_multi_vendor-2a2dc0854589/app/controllers/spree/api/v1/vendors_controller.rb:1:in `<main>'
	from /bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /bundle/ruby/3.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:30:in `require'
	from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
	from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/loader/helpers.rb:135:in `cget'
	from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/loader/eager_load.rb:175:in `block in actual_eager_load_dir'
	from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
	from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/loader/helpers.rb:25:in `each'
	from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/loader/helpers.rb:25:in `ls'
	from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/loader/eager_load.rb:170:in `actual_eager_load_dir'
	from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
	from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/loader/eager_load.rb:16:in `each'
	from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
	from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
	from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
	from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/loader.rb:379:in `block in eager_load_all'
	from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/loader.rb:377:in `each'
	from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/loader.rb:377:in `eager_load_all'
	from /bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/application/finisher.rb:74:in `block in <module:Finisher>'
	from /bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `instance_exec'
	from /bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `run'
	from /bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
	from /bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:60:in `run_initializers'
	from /bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/application.rb:372:in `initialize!'
	from /app/config/environment.rb:5:in `<main>'
	from /bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /bundle/ruby/3.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /bundle/ruby/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
	from /bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/application.rb:348:in `require_environment!'
	from /bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/command/actions.rb:28:in `require_environment!'
	from /bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	from /bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/commands/generate/generate_command.rb:21:in `perform'
	from /bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/command/base.rb:87:in `perform'
	from /bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/command.rb:48:in `invoke'
	from /bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/commands.rb:18:in `<main>'
	from /bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/app_loader.rb:59:in `block in exec_app'
	from /bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/app_loader.rb:48:in `loop'
	from /bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/app_loader.rb:48:in `exec_app'
	from /bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/cli.rb:7:in `<top (required)>'
	from /bundle/ruby/3.2.0/gems/railties-7.0.8/exe/rails:10:in `require'
	from /bundle/ruby/3.2.0/gems/railties-7.0.8/exe/rails:10:in `<top (required)>'
	from /bundle/ruby/3.2.0/bin/rails:25:in `load'
	from /bundle/ruby/3.2.0/bin/rails:25:in `<top (required)>'
	from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:491:in `exec'
	from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.1/libexec/bundle:45:in `block in <top (required)>'
	from /usr/local/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.1/libexec/bundle:33:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:25:in `load'
	from /usr/local/bundle/bin/bundle:25:in `<main>'
```

**Comment by poudelprakash** [comment]
I am also facing same issue, did you get this resolved?

**Comment by amit-dhoundiyal** [comment]
Any Update on this. I am also getting the same error.

 Both Spree::Product and its :status machine have defined a different default for "status". Use only one or the other for defining defaults to avoid unexpected behaviors.
 Exiting
 /usr/local/bundle/gems/spree_multi_vendor-2.4.0/app/controllers/spree/api/v1/vendors_controller.rb:4:in `<module:V1>': uninitialized constant Spree::Api::V1::BaseController (NameError)

       class VendorsController < Spree::Api::V1::BaseController
                                               ^^^^^^^^^^^^^^^^
 Did you mean?  Spree::BaseSorter
 	from /usr/local/bundle/gems/spree_multi_vendor-2.4.0/app/controllers/spree/api/v1/vendors_controller.rb:3:in `<module:Api>'
 	from /usr/local/bundle/gems/spree_multi_vendor-2.4.0/app/controllers/spree/api/v1/vendors_controller.rb:2:in `<module:Spree>'
 	from /usr/local/bundle/gems/spree_multi_vendor-2.4.0/app/controllers/spree/api/v1/vendors_controller.rb:1:in `<main>'
 	from /usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
 	from /usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
 	from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
 	from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:30:in `require'
 	from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
 	from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/helpers.rb:135:in `cget'
 	from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
 	from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
 	from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/helpers.rb:25:in `each'
 	from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/helpers.rb:25:in `ls'
 	from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
 	from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
 	from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:16:in `each'
 	from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
 	from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
 	from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
 	from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader.rb:329:in `block in eager_load_all'
 	from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader.rb:327:in `each'
 	from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader.rb:327:in `eager_load_all'
 	from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
 	from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/initializable.rb:32:in `instance_exec'
 	from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/initializable.rb:32:in `run'
 	from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/initializable.rb:61:in `block in run_initializers'
 	from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
 	from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
 	from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
 	from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
 	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
 	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
 	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
 	from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
 	from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
 	from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/initializable.rb:60:in `run_initializers'
 	from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/application.rb:391:in `initialize!'
 	from /app/config/environment.rb:7:in `<main>'
 	from config.ru:5:in `require_relative'
 	from config.ru:5:in `block in <main>'
 	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/builder.rb:116:in `eval'
 	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/builder.rb:116:in `new_from_string'
 	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/builder.rb:105:in `load_file'
 	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/builder.rb:66:in `parse_file'
 	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:349:in `build_app_and_options_from_config'
 	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:249:in `app'
 	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:422:in `wrapped_app'
 	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:312:in `block in start'
 	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:379:in `handle_profiling'
 	from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:311:in `start'
 	from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/commands/server/server_command.rb:39:in `start'
 	from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/commands/server/server_command.rb:144:in `block in perform'
 	from <internal:kernel>:90:in `tap'
 	from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/commands/server/server_command.rb:135:in `perform'
 	from /usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
 	from /usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
 	from /usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
 	from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/command/base.rb:69:in `perform'
 	from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/command.rb:48:in `invoke'
 	from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/commands.rb:18:in `<main>'
 	from /usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
 	from /usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
 	from bin/rails:7:in `<main>'

**Comment by codemaverick32** [comment]
> Any Update on this. I am also getting the same error.
> 
> Both Spree::Product and its :status machine have defined a different default for "status". Use only one or the other for defining defaults to avoid unexpected behaviors. Exiting /usr/local/bundle/gems/spree_multi_vendor-2.4.0/app/controllers/spree/api/v1/vendors_controller.rb:4:in `module:V1': uninitialized constant Spree::Api::V1::BaseController (NameError)
> 
> ```
>    class VendorsController < Spree::Api::V1::BaseController
>                                            ^^^^^^^^^^^^^^^^
> ```
> 
> Did you mean? Spree::BaseSorter from /usr/local/bundle/gems/spree_multi_vendor-2.4.0/app/controllers/spree/api/v1/vendors_controller.rb:3:in `<module:Api>' from /usr/local/bundle/gems/spree_multi_vendor-2.4.0/app/controllers/spree/api/v1/vendors_controller.rb:2:in `module:Spree' from /usr/local/bundle/gems/spree_multi_vendor-2.4.0/app/controllers/spree/api/v1/vendors_controller.rb:1:in `<main>' from /usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require' from /usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require' from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require' from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:30:in `require' from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/helpers.rb:135:in `const_get' from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/helpers.rb:135:in `cget' from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir' from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/helpers.rb:40:in `block in ls' from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/helpers.rb:25:in `each' from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/helpers.rb:25:in `ls' from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir' from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load' from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:16:in `each' from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load' from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize' from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load' from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader.rb:329:in `block in eager_load_all' from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader.rb:327:in `each' from /usr/local/bundle/gems/zeitwerk-2.6.8/lib/zeitwerk/loader.rb:327:in `eager_load_all' from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>' from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/initializable.rb:32:in `instance_exec' from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/initializable.rb:32:in `run' from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/initializable.rb:61:in `block in run_initializers' from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each' from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component' from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from' from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component' from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each' from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call' from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component' from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each' from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each' from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/initializable.rb:60:in `run_initializers' from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/application.rb:391:in `initialize!' from /app/config/environment.rb:7:in `
> 
> '
> from config.ru:5:in `require_relative' from config.ru:5:in `block in '
> from /usr/local/bundle/gems/rack-2.2.7/lib/rack/builder.rb:116:in `eval' from /usr/local/bundle/gems/rack-2.2.7/lib/rack/builder.rb:116:in `new_from_string'
> from /usr/local/bundle/gems/rack-2.2.7/lib/rack/builder.rb:105:in `load_file' from /usr/local/bundle/gems/rack-2.2.7/lib/rack/builder.rb:66:in `parse_file'
> from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:349:in `build_app_and_options_from_config' from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:249:in `app'
> from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:422:in `wrapped_app' from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:312:in `block in start'
> from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:379:in `handle_profiling' from /usr/local/bundle/gems/rack-2.2.7/lib/rack/server.rb:311:in `start'
> from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/commands/server/server_command.rb:39:in `start' from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/commands/server/server_command.rb:144:in `block in perform'
> from internal:kernel:90:in `tap' from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/commands/server/server_command.rb:135:in `perform'
> from /usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:27:in `run' from /usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
> from /usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch' from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/command/base.rb:69:in `perform'
> from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/command.rb:48:in `invoke' from /usr/local/bundle/gems/railties-6.1.7.4/lib/rails/commands.rb:18:in `'
> from /usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require' from /usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
> from bin/rails:7:in `'

@damianlegawiec Please help.

**Comment by damianlegawiec** [comment]
@codemaverick32 @amit-dhoundiyal  you need to add `spree_api_v1` gem to your gemfile, before `spree_multi_vendor`
