### ISSUE TITLE
I am confused

### ISSUE THREAD

**Issue by Gursehaj** [spree/spree_multi_vendor#232]
I am confused, is this extension an opensource extension (it should be, it's on Github) or not? Do I need to buy a license from Vendo to use it?

**Comment by damianlegawiec** [comment]
Hey @Gursehaj 

This extension is free & open source and distributed via [BSD License](https://github.com/spree-contrib/spree_multi_vendor/blob/main/LICENSE).

However, we don't actively maintain it or add new features anymore. You're free to use it, modify it, and so on. We don't guarantee that it will work with newer Spree versions, though.

README includes a comparison about what is included in this extension vs [Vendo](https://getvendo.com).
