### ISSUE TITLE
Add high-level description

### ISSUE THREAD

**Issue by 0xtmphey** [spree/spree_multi_vendor#26]
Hello! 
I have installed this extension and now can see `vendors` tab in my admin panel.
Also, i can fill vendor field when creating user, but then i am stack. 
It would be cool if you, guys, can provide some description how your extension works and how to use it =)

**Comment by hugohernani** [comment]
I'm also interested in getting more info on how this extension works.
Are you able to give us some explanation, @symarys ? =)

**Comment by symarys** [comment]
@hugohernani In general this extension adds a new Spree::Vendor model. Vendors can be managed via admin (`admin/vendors`). Also, you can assign option types, products, properties, shipping methods and stock locations to a specific vendor (using vendor field on e.g. admin product path). 
When a user has one or more vendors assigned to their account, they can manage their data in the admin panel (they can see their vendors' products, orders containing these products, etc.).

**Comment by jose2007kj** [comment]
@symarys @damianlegawiec hi,  i would like to know,if there is seperate login/registration page for vendors,thanks

**Comment by symarys** [comment]
Hey Jose, there's no separate page, it's the same for all the users. A vendor cannot register as a vendor through registration page though, only as a user. You can make a vendor from a user only via admin panel.

**Comment by jose2007kj** [comment]
@symarys    thankyou Maria for the info

**Comment by ghost** [comment]
@symarys  As per my understanding this gem is needed 

- when there is one super admin and so many vendors. 
- every single vendor will manage his own store.
- A vendor can login thorough a particular user credential.

My query is that how a particular store will be attach to a particular vendor ?

For example there is a vendor-1 and he wanted to create and host a store in vendor1.example.com domain and there is a vendor-2 and he wanted a separate store on vendor2.example.com how they can do this ?

**Comment by symarys** [comment]
@ancdbcs This extension does not have this type of functionality, there's no relation between a vendor and a store. You can only have different products from different vendors within one store.

**Comment by ghost** [comment]
@symarys thanks for confirming me. 

But my requirements is to have separate store for each vendor with one super admin.

_As I mentioned there is a vendor-1 and he wanted to create and host a store in vendor1.example.com domain with his products and there is a vendor-2 and he wanted a separate store on vendor2.example.com with his products how they can do this ?_

Will you please guide me how I can do this I am not finding any solution on internet for that from long time. Is spree provide any solution for that or I need to do customization?

**Comment by kudapara** [comment]
@ancdbcs did you end up getting the solution?

I am also curious how payments are handled. Will each vendor use their own payment gateway or all the money comes to the admin's account who then has the responsibility to distribute the funds to the vendors?

Is there a way to do automatic split payments, say 2% of every order goes to the admin's account while the rest goes to the vendors?
