### ISSUE TITLE
Forbidden/Unauthorized Routes

### ISSUE THREAD

**Issue by addzep** [spree/spree_multi_vendor#42]
In vendor setting, there are links such as "Digital Variants", "Translation". On Order screen other than "Customer" and "Shipment" no route works, it shows "Forbidden" or "Unauthorized".

There errors are only in Vendor Admin Area.

**Comment by damianlegawiec** [comment]
@addzep those routes / admin features are part of different spree extensions - you will need to prepare and apply a custom ability class to make them available for Vendors

**Comment by addzep** [comment]
@damianlegawiec Thank you, then by default they should not be visible to vendors? And is there any documentation to do so?
