### ISSUE TITLE
undefined method `commission_rate' for nil:NilClass

### ISSUE THREAD

**Issue by htorohn** [spree/spree_multi_vendor#67]
Hello,

i just installed the extension and was testing it but run into this problem at checkout.

NoMethodError in Spree::CheckoutController#update
undefined method `commission_rate' for nil:NilClass
Extracted source (around line #19):

order.line_items.includes(product: :vendor).group_by{ |li| li.product.vendor }.each do |vendor, vendor_line_items|
          order.commissions.create(
              amount: vendor_line_items.pluck(:pre_tax_amount).sum * vendor.commission_rate / 100,
              vendor_id: vendor.id
          )
        end
Steps i made:

- I created a user and assigned it to a vendor, the i create a product with that user.
- With another user, i shopped one product from default user and the product I added in the previous step.
- i did check out and enter the shipping information.
- I selected one shipping method for the first item and a different method for the second product.
- I selected check as the payment method and when I click save and continue I get the error!

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree-contrib/spree_multi_vendor/pull/69
