### ISSUE TITLE
Could not find generator 'spree_multi_vendor:install'

### ISSUE THREAD

**Issue by fanon** [spree/spree_multi_vendor#84]
Am try to  run the multi_vendor extension on my localhost as per instructions on github and running into the  error:

Could not find generator 'spree_multi_vendor:install'. Maybe you meant 'spree_gateway:install', 'spree:auth:install' or 'spree:install'

Am on: Rails 5.2.3 an ruby:ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

What would be the issue?

**Comment by kobeumut** [comment]
I have the same problem. I try rails 6 with ruby 2.6.3 and rails 5.2.3 with ruby 2.5.5 version but gets same error

**Comment by rdutra** [comment]
Same problem here, I can get the migrations to download and run them manually 
but the generator is just not there unless you run
bundle exec rake railties:install:migrations FROM=spree_multi_vendor
and 
bundle exec rake spree_multi_vendor:sample:create

first

**Comment by damianlegawiec** [comment]
this is fixed in 2.0 :)
