### ISSUE TITLE
Same product from multiple Vendors

### ISSUE THREAD

**Issue by heroic** [spree/spree_multi_vendor#97]
How would I allow the product to be sold by multiple vendors?

**Comment by binnyFriedman** [comment]
Hey  @heroic I was looking for the same thing and from what i understand on [this thread](https://spree-commerce.slack.com/archives/C0HUDSW5V/p1551835016016900) it is not available out of the box and requires extra development

**Comment by damianlegawiec** [comment]
So there are several ways to do it, the easiest would be to vendorize Variants not Products and let Vendor have their own Variant fo the same product.

**Comment by damianlegawiec** [comment]
In 2.0 you can simply configure it to:

```ruby
SpreeMultiVendor::Config[:vendorized_models] = %w[variant stock_location shipping_method]
```

**Comment by zolzaya** [comment]
hey @damianlegawiec 
vendorized models are not work. I created an issue. https://github.com/spree-contrib/spree_multi_vendor/issues/171

**Comment by helmiItsavirus** [comment]
@damianlegawiec The issue happened to me as well.

is there any idea to make a limitation on `vendorized_models`?
